jhmcConfig:
  noboom:
    # 取值 true 或 false
    enable_noboom: true       # 开启防爆
    allow_tnt: false          # 允许TNT爆炸
    allow_crepper: false      # 允许爬行者爆炸
    allow_tnt_minecart: false # 允许TNT矿车爆炸
    cmd_onlyServer: true      # 防爆开关指令仅后台执行
